name = "Everglow"
author = "OdysseusSSB"
version = "[Dev]"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e1fc2f49025bf0c1c9487ebe63c8591cf0d9fe4700af39775e6666367b87072"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
