name = "Everglow"
author = "OdysseusSSB"
version = "[Dev]"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c271e009c25771925f2086e38cb1e229fc863842c4202f6d842c33ae67c55145"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = []
datapack-folder = "config/paxi/datapacks"
