name = "Everglow"
author = "OdysseusSSB"
version = "[Dev]"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2d4001be62a8af829415fb016d2d8f954ce45f974865ba6890afe709d49d2a7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"

[options]
acceptable-game-versions = []
datapack-folder = "config/paxi/datapacks"
