
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.stone_type]

		[types.stone_type.atmospheric]
			ivory_travertine = true
			peach_travertine = true
			persimmon_travertine = true
			saffron_travertine = true
			dolerite = true

		[types.stone_type.quark]
			soul_sandstone = true
			limestone = true
			jasper = true
			shale = true
			myalite = true
			permafrost = true

		[types.stone_type.spelunkery]
			nephrite = true

		[types.stone_type.windswept]
			shale = true

		[types.stone_type.caverns_and_chasms]
			sugilite = true

		[types.stone_type.oreganized]
			glance = true

	[types.wood_type]

		[types.wood_type.caverns_and_chasms]
			azalea = true

		[types.wood_type.netherexp]
			claret = true
			smokestalk = true

		[types.wood_type.mynethersdelight]
			powdery = true

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.windswept]
			holly = true
			chestnut = true
			pine = true

		[types.wood_type.environmental]
			willow = true
			pine = true
			plum = true
			wisteria = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.endergetic]
			poise = true

		[types.wood_type.moresnifferflowers]
			corrupted = true
			vivicus = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			aspen = true
			laurel = true
			kousa = true
			grimwood = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.sullysmod]
			petrified = true

		[types.wood_type.collectorsreap]
			lucuma = true

	[types.leaves_type]

		[types.leaves_type.windswept]
			holly = true
			chestnut = true
			pine = true
			flowering_acacia = true

		[types.leaves_type.environmental]
			hibiscus = true
			willow = true
			pine = true
			plum = true
			cheerful_plum = true
			moody_plum = true
			wisteria = true
			pink_wisteria = true
			blue_wisteria = true
			purple_wisteria = true
			white_wisteria = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.moresnifferflowers]
			corrupted = true
			vivicus = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			aspen = true
			green_aspen = true
			laurel = true
			dry_laurel = true
			kousa = true
			currant = true
			grimwood = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.collectorsreap]
			lucuma = true

	[types.cake]

		[types.cake.neapolitan]
			vanilla_cake = true
			chocolate_cake = true
			strawberry_cake = true
			banana_cake = true
			mint_cake = true
			adzuki_cake = true

		[types.cake.exquisito]
			chorus_cake = true
			ether_bulb_cake = true
			jelly_ring_cake = true
			nightshade_berry_cake = true
			zure_berry_cake = true

		[types.cake.seasonals]
			pumpkin_cake = true
			sweet_berry_cake = true
			beetroot_cake = true

		[types.cake.peculiars]
			yucca_cake = true
			aloe_cake = true
			passion_fruit_cake = true

		[types.cake.mynethersdelight]
			magma_cake = true

		[types.cake.collectorsreap]
			lime_cake = true
			pomegranate_cake = true
			pink_dragon_fruit_cake = true
			lucuma_cake = true

		[types.cake.ubesdelight]
			ube_cake = true

#Disables specific entries
[entries]

	[entries.stone_type]

		[entries.stone_type.quark]
			pillar = true
			polished_vertical_slab = true
			vertical_slab = true

	[entries.mud_type]

		[entries.mud_type.quark]
			carved_bricks = true
			pillar = true
			brick_lattice = true

	[entries.wood_type]

		[entries.wood_type.woodworks]
			bookshelf = true
			chiseled_bookshelf = true
			trapped_chest = true
			boards = true
			chest = true
			ladder = true
			beehive = true

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			hollow_log = true
			vertical_slab = true

		[entries.wood_type.boatload]
			large_boat = true
			furnace_boat = true

		[entries.wood_type.farmersdelight]
			cabinet = true

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.woodworks]
			leaf_pile = true

