#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Apr 14 12:11:34 AEST 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=16
shaderPack=Shrimple_v0.11.zip
enableShaders=false
